<?php

namespace App\Model\Orm\Repository;

use App\Model\Orm\Entity\UsersRatings;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

class UsersRatingsRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, string $entityClass = UsersRatings::class)
    {
        parent::__construct($em, $em->getClassMetadata($entityClass));
    }

    public function findOneBy(array $criteria, ?array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
    }

    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function save(UsersRatings $usersRatings)
    {
        $this->getEntityManager()->persist($usersRatings);
        $this->getEntityManager()->flush();

    }

    public function remove(UsersRatings $usersRatings)
    {
        $this->getEntityManager()->remove($usersRatings);
        $this->getEntityManager()->flush();

    }
}